 spring:
  application:
    name: api-gateway  # Define the application name

  server:
    port: 8080  # API Gateway will run on port 8080

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # Load-balanced URI for user-service
          predicates:
            - Path=/users/**  # Route pattern for user-service

        - id: order-service
          uri: lb://order-service  # Load-balanced URI for order-service
          predicates:
            - Path=/orders/**  # Route pattern for order-service

        - id: inventry-service
          uri: lb://inventry-service  # Load-balanced URI for inventory-service
          predicates:
            - Path=/inventory/**  # Route pattern for inventory-service

 eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
 